import requests

from ai.prompts import COMPANION_PROMPT
from config import LM_STUDIO_BASE_URL, LM_STUDIO_MODEL
from memory_system.memory import remember, load_memory
from ai.ai_extractor import extract_memory_with_ai


def build_messages(message, history):
    messages = [
        {
            "role": "system",
            "content": COMPANION_PROMPT
        }
    ]

    memory = load_memory()

    if memory:
        memory_text = "Known facts about the player:\n"

        for key, value in memory.items():
            memory_text += f"- {key}: {value}\n"

        messages.append(
            {
                "role": "system",
                "content": memory_text
            }
        )

    for item in history:
        role = item["role"]
        content = item["content"]

        if isinstance(content, list):
            content = content[0]["text"]

        if role in ["user", "assistant"]:
            messages.append(
                {
                    "role": role,
                    "content": content
                }
            )

    messages.append(
        {
            "role": "user",
            "content": message
        }
    )

    return messages


def clean_ai_response(text):
    """
    Remove unwanted conversation continuations generated by the model.
    """

    unwanted_markers = [
        "\nUser:",
        "\nUser",
        "\nAssistant:",
        "\nAssistant"
    ]

    for marker in unwanted_markers:
        if marker in text:
            text = text.split(marker, 1)[0]

    return text.strip()


def ask_lm_studio(messages):
    url = f"{LM_STUDIO_BASE_URL}/chat/completions"

    payload = {
        "model": LM_STUDIO_MODEL,
        "messages": messages,
        "temperature": 0.7,
        "max_tokens": 120
    }

    response = requests.post(
        url,
        json=payload,
        timeout=30
    )

    response.raise_for_status()

    data = response.json()

    answer = data["choices"][0]["message"]["content"]

    return clean_ai_response(answer)


def ask_ai(message, history):
    facts = extract_memory_with_ai(message)

    for key, value in facts.items():
        remember(key, value)

    messages = build_messages(message, history)

    return ask_lm_studio(messages)